### ISSUE TITLE
Cant Open The client

### ISSUE THREAD

**Issue by itsreyi** [sssssssthedev/SmartClient#11]
i installed the liberies but this error pup up
![image](https://github.com/sssssssthedev/SmartClient/assets/136232606/f50a87a0-be6d-458d-99ee-ebb404ecb849)

**Comment by itsreyi** [comment]
also added this 
![image](https://github.com/sssssssthedev/SmartClient/assets/136232606/5df19acf-f904-4f6b-abe8-3e956d5c8d00)

**Comment by sssssssthedev** [comment]
Client is not supported by me anymore, i'm working on a new 1.12 release but thats gonna be in a long time, for now you can use the mkleaks fork (https://github.com/MkLeaks/SmartClient)
