### ISSUE TITLE
Libraries Isnt Working

### ISSUE THREAD

**Issue by DarkClever** [sssssssthedev/SmartClient#2]
https://libraries.minecraft.net/de/enzaxd/viaforge:ViaForge/enzaxd-viaforge:ViaForge.jar -> 

C:\Users\Secret\AppData\Roaming\.minecraft\libraries\de\enzaxd\viaforge:ViaForge\enzaxd-viaforge:ViaForge.jar : The filename, directory name, or volume label syntax is incorrect

**Comment by sssssssthedev** [comment]
Seems like I did something wrong in the json, will check when i get home.

**Comment by sssssssthedev** [comment]
I have checked the json and run the client on my end, no issues whatsover related to that, its probably something on your side. Try to install the libraries from the .zip file in the readme.

**Comment by sssssssthedev** [comment]
Closed due to no response, its works perfectly on my side, probably your json is wrong or something else related to your environment.
