### ISSUE TITLE
Client will crash when trying to launch 

### ISSUE THREAD

**Issue by Disguised9** [sssssssthedev/SmartClient#3]
Launcher will try to download libraries but one of the links is broken even though the smart libraries have been installed, tested on SK Launcher and Multi MC wouldn't launch, if there's a way to contact you i would be grateful because don't know if it's my issue or it's the client itself

![unknown-253](https://user-images.githubusercontent.com/99958507/163689572-098bfc68-dba9-44b2-9fda-2c31200aaa42.png)

**Comment by sssssssthedev** [comment]
Check if you have the enzaxd-viaforge-ViaForge.jar in the .minecraft/libraries/de/enzaxd/viaforge folder. It works on my side fine withouth any library issues, I need to fix the fact that mc doesn't start up if you don't use java 11 because the jar is only compiled for java 11.

**Comment by Disguised9** [comment]
Thanks for the response but i already have installed java 18 but for some reason it crashes and i do have the file in /libraries/de/enzaxd/viaforge

**Comment by sssssssthedev** [comment]
The thing is, that shouldn't happen, if you have the correct .json it should just get the library from that folder, if that errors then it means you either don't have that folder or the .json is wrong.

**Comment by sssssssthedev** [comment]
Closed due to inactivity
