### ISSUE TITLE
Client doesn't start bcs error.

### ISSUE THREAD

**Issue by ghost** [sssssssthedev/SmartClient#4]
![photo_2022-04-25_19-07-07](https://user-images.githubusercontent.com/43071315/165138623-b558c54b-9f40-4894-b413-4fa8357d7452.jpg)
![photo_2022-04-25_19-06-58](https://user-images.githubusercontent.com/43071315/165138624-deb54011-ed52-487f-b436-66114a6db858.jpg)
![photo_2022-04-25_19-07-02](https://user-images.githubusercontent.com/43071315/165138626-de700891-fa34-41f3-830f-018e6a097f51.jpg)

**Comment by sssssssthedev** [comment]
Weird, I just set the java executable in the installation to my jdk java.exe and it worked.

**Comment by lucadado** [comment]
what java u use?

**Comment by vuccinett** [comment]
same problem using the jar and the json provided in last build

**Comment by sssssssthedev** [comment]
![kcDgygEv](https://user-images.githubusercontent.com/69808781/167345052-a799aa15-d09a-4fc8-b57e-24327381d935.png)

**Comment by sssssssthedev** [comment]
Closed due to inactivity
