### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by vuccinett** [sssssssthedev/SmartClient#5]
Using smart client version 1.2.9 and it doesnt work for some reason it says
![image](https://user-images.githubusercontent.com/85068126/167315293-bc1777b4-6d2b-4c80-99f1-a76f62837d97.png)
then i press ok and it says
![image](https://user-images.githubusercontent.com/85068126/167315306-435879c1-14e0-43b0-bb08-da5f3fbc7cc4.png)
When i reload the launcher it says that it is caused by a non valid config of the java runtime environment but its weird because it just happened to my friend too

**Comment by vuccinett** [comment]
also i installed  all the libraries needed in the file provided putting them in the folder libraries

**Comment by sssssssthedev** [comment]
You need to add java 11 as java executable.

**Comment by sssssssthedev** [comment]
![kcDgygEv](https://user-images.githubusercontent.com/69808781/167345013-06cd47d5-497d-4613-9072-cb868577b300.png)

**Comment by vuccinett** [comment]
wont work with Java 17?

**Comment by sssssssthedev** [comment]
I am gonna make it so it works withouth doing that, but i'm bot maintaning the project that much because of personal issues, also any java above 11 should work.

**Comment by vuccinett** [comment]
I tried like you said using the java exe (jdk 17). It opened a cmd that closed after a few seconds and then it crashes opening the launcher with this error:

The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: net/arikia/dev/drpc/DiscordEventHandlers$Builder
Exit code: -1

**Comment by vuccinett** [comment]
Ok i figured out the error some libraries were not installed,so i installed them and now it works!
