### ISSUE TITLE
Issue with the client

### ISSUE THREAD

**Issue by underguessr** [sssssssthedev/SmartClient#6]
Alr from what I can see this error has occured on multiple pc's so I'll just get on with it. The error is the JNI thing and it says that my java is not the same as the java used to build the jar. And then I checked out one of the issues on the repository and you said that you use/d java version 11.0.10. And i looked up my version and its this: 
![image](https://user-images.githubusercontent.com/87640458/178327151-5f05cfbf-2929-4f69-bfaa-d934e14e42aa.png)
I don't understand why it won't run as I am using identically the same version as you are. Feel free to respond at any time. Thanks. :)

**Comment by sssssssthedev** [comment]
You have to set java executable to java 11 in the instace settings

**Comment by sssssssthedev** [comment]
https://user-images.githubusercontent.com/69808781/167345052-a799aa15-d09a-4fc8-b57e-24327381d935.png

**Comment by sssssssthedev** [comment]
Closed due to inactivity
