### ISSUE TITLE
I cant start the client

### ISSUE THREAD

**Issue by Atisgamer08** [sssssssthedev/SmartClient#7]
Client crashes when i try to start the client:
![image](https://user-images.githubusercontent.com/74657572/185991754-4a7ac7c2-3b2a-4e8d-b0af-4005d2938898.png)

Help please.

**Comment by sssssssthedev** [comment]
Missing libraries, weird that google json library is missing though.

**Comment by sssssssthedev** [comment]
Ok so it seems that is missing because you didn't download smartlibraries from the main readme and put them in .libraries in your .minecraft folder

**Comment by sssssssthedev** [comment]
Closed due to inactivity
