### ISSUE TITLE
SmartClient cannot launched

### ISSUE THREAD

**Issue by xPutraGm** [sssssssthedev/SmartClient#8]
So when i was launched my SmartClient this messages is appear on my screen so i need help!
**Launcher: TLauncher**

![image](https://user-images.githubusercontent.com/70950584/189051136-c5bd2af2-7113-4e1f-8bc5-2d1bd7e6c3a1.png) 
![image](https://user-images.githubusercontent.com/70950584/189050672-494981c6-287a-45c4-bfe3-725d9920d04c.png)
![image](https://user-images.githubusercontent.com/70950584/189050729-b1181910-6945-4292-9fa0-3526e47e70a2.png) 

**[EDIT] Now its fixed because i use another client and change java path to java.exe**

**Comment by sssssssthedev** [comment]
Fixed by OP.
